// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Dicts from "../../../src/Dicts.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("dict<string>", t => {
  let data = {
    key1: "value1",
    key2: "value2"
  };
  let json = {
    key1: "value1",
    key2: "value2"
  };
  let encoded = Dicts.stringDict_encode(data);
  testEqual(t, "encode string dict", encoded, json);
  let decoded = Dicts.stringDict_decode(json);
  testEqual(t, "decode string dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("dict<int>", t => {
  let data = {
    a: 1,
    b: 2,
    c: 3
  };
  let json = {
    a: 1.0,
    b: 2.0,
    c: 3.0
  };
  let encoded = Dicts.intDict_encode(data);
  testEqual(t, "encode int dict", encoded, json);
  let decoded = Dicts.intDict_decode(json);
  testEqual(t, "decode int dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("dict<inner>", t => {
  let data = {
    first: {
      id: 1,
      name: "Alice"
    },
    second: {
      id: 2,
      name: "Bob"
    }
  };
  let json = {
    first: {
      id: 1.0,
      name: "Alice"
    },
    second: {
      id: 2.0,
      name: "Bob"
    }
  };
  let encoded = Dicts.innerDict_encode(data);
  testEqual(t, "encode inner dict", encoded, json);
  let decoded = Dicts.innerDict_decode(json);
  testEqual(t, "decode inner dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("empty dict", t => {
  let data = {};
  let json = {};
  let encoded = Dicts.stringDict_encode(data);
  testEqual(t, "encode empty dict", encoded, json);
  let decoded = Dicts.stringDict_decode(json);
  testEqual(t, "decode empty dict", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("Dict.t<string>", t => {
  let data = {
    foo: "bar"
  };
  let json = {
    foo: "bar"
  };
  let encoded = Dicts.dictT_encode(data);
  testEqual(t, "encode Dict.t", encoded, json);
  let decoded = Dicts.dictT_decode(json);
  testEqual(t, "decode Dict.t", decoded, {
    TAG: "Ok",
    _0: data
  });
});

Zora.test("dict<option<string>>", t => {
  let data = {
    present: "value",
    missing: undefined
  };
  let encoded = Dicts.optionStringDict_encode(data);
  testEqual(t, "encode omits None values", encoded, {
    present: "value"
  });
  let decoded = Dicts.optionStringDict_decode({
    present: "value",
    missing: null
  });
  t.test("decode present null values as None", async t => {
    if (decoded.TAG === "Ok") {
      let dict = decoded._0;
      t.equal(dict["present"], "value", "present");
      let hasOwnProperty = ((obj, key) => Object.prototype.hasOwnProperty.call(obj, key));
      let getValue = ((obj, key) => obj[key]);
      let hasMissing = hasOwnProperty(dict, "missing");
      let missingValue = getValue(dict, "missing");
      t.equal(hasMissing, true, "missing key is present");
      t.equal(missingValue, undefined, "missing");
      return;
    }
    t.fail("expected decode to succeed");
  });
});

export {
  testEqual,
}
/*  Not a pure module */
