// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Spice from "../../../src/Spice.mjs";
import * as GenericTypeParams from "../../../src/GenericTypeParams.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

let dataObject = {
  properties: [
    "one",
    "two"
  ]
};

let dataObjectJson = {
  properties: [
    "one",
    "two"
  ]
};

let pairObject = {
  left: "count",
  right: 42
};

let pairObjectJson = {
  left: "count",
  right: 42.0
};

let nestedObject_items = [dataObject];

let nestedObject_selected = "one";

let nestedObject = {
  items: nestedObject_items,
  selected: nestedObject_selected
};

let nestedObjectJson = {
  items: [dataObjectJson],
  selected: "one"
};

Zora.test("generic type parameter codecs", t => {
  testEqual(t, `encode generic record`, GenericTypeParams.dataObject_encode(Spice.stringToJson)(dataObject), dataObjectJson);
  testEqual(t, `decode generic record`, GenericTypeParams.dataObject_decode(Spice.stringFromJson)(dataObjectJson), {
    TAG: "Ok",
    _0: dataObject
  });
  testEqual(t, `encode record with two generic params`, GenericTypeParams.pairObject_encode(Spice.stringToJson)(Spice.intToJson)(pairObject), pairObjectJson);
  testEqual(t, `decode record with two generic params`, GenericTypeParams.pairObject_decode(Spice.stringFromJson)(Spice.intFromJson)(pairObjectJson), {
    TAG: "Ok",
    _0: pairObject
  });
  testEqual(t, `encode nested generic record`, GenericTypeParams.nestedObject_encode(Spice.stringToJson)(nestedObject), nestedObjectJson);
  testEqual(t, `decode nested generic record`, GenericTypeParams.nestedObject_decode(Spice.stringFromJson)(nestedObjectJson), {
    TAG: "Ok",
    _0: nestedObject
  });
});

export {
  testEqual,
  dataObject,
  dataObjectJson,
  pairObject,
  pairObjectJson,
  nestedObject,
  nestedObjectJson,
}
/*  Not a pure module */
