// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as TopLevelOptions from "../../../src/TopLevelOptions.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

function optionRecord() {
  return {
    title: "payload",
    optionalAlias: Primitive_option.some(undefined),
    aliases: [
      "alias",
      undefined
    ],
    tuple: [
      "tuple",
      undefined
    ],
    result: {
      TAG: "Error",
      _0: undefined
    }
  };
}

function optionRecordJson() {
  return {
    title: "payload",
    optionalAlias: null,
    aliases: [
      "alias",
      null
    ],
    tuple: [
      "tuple",
      null
    ],
    result: [
      "Error",
      null
    ]
  };
}

function nestedTuple() {
  return [
    {
      title: "payload",
      optionalAlias: Primitive_option.some(undefined),
      aliases: [
        "alias",
        undefined
      ],
      tuple: [
        "tuple",
        undefined
      ],
      result: {
        TAG: "Error",
        _0: undefined
      }
    },
    {
      title: "payload",
      optionalAlias: Primitive_option.some(undefined),
      aliases: [
        "alias",
        undefined
      ],
      tuple: [
        "tuple",
        undefined
      ],
      result: {
        TAG: "Error",
        _0: undefined
      }
    },
    undefined,
    "plain",
    [
      "array",
      undefined
    ],
    {
      TAG: "Ok",
      _0: "result"
    }
  ];
}

function nestedTupleJson() {
  return [
    optionRecordJson(),
    optionRecordJson(),
    null,
    "plain",
    [
      "array",
      null
    ],
    [
      "Ok",
      "result"
    ]
  ];
}

function payloadVariantJson() {
  return [
    "Payload",
    null,
    null,
    optionRecordJson()
  ];
}

Zora.test("top-level option", t => {
  let encodedSome = TopLevelOptions.mystring_encode("value");
  testEqual(t, `encode Some`, encodedSome, "value");
  let encodedNone = TopLevelOptions.mystring_encode(undefined);
  testEqual(t, `encode None`, encodedNone, undefined);
  let decodedSome = TopLevelOptions.mystring_decode("value");
  testEqual(t, `decode Some`, decodedSome, {
    TAG: "Ok",
    _0: "value"
  });
  let decodedNone = TopLevelOptions.mystring_decode(null);
  testEqual(t, `decode null`, decodedNone, {
    TAG: "Ok",
    _0: undefined
  });
});

Zora.test("top-level option of nested record", t => {
  let payload_optionalAlias = Primitive_option.some(undefined);
  let payload_aliases = [
    "alias",
    undefined
  ];
  let payload_tuple = [
    "tuple",
    undefined
  ];
  let payload_result = {
    TAG: "Error",
    _0: undefined
  };
  let payload = {
    title: "payload",
    optionalAlias: payload_optionalAlias,
    aliases: payload_aliases,
    tuple: payload_tuple,
    result: payload_result
  };
  let payloadJson = optionRecordJson();
  let encodedSome = TopLevelOptions.maybeOptionRecord_encode(payload);
  testEqual(t, `encode Some nested record`, encodedSome, payloadJson);
  let encodedNone = TopLevelOptions.maybeOptionRecord_encode(undefined);
  testEqual(t, `encode None as absence`, encodedNone, undefined);
  let encodedJsonSome = TopLevelOptions.maybeOptionRecord_encodeJson(payload);
  testEqual(t, `encodeJson Some nested record`, encodedJsonSome, payloadJson);
  let encodedJsonNone = TopLevelOptions.maybeOptionRecord_encodeJson(undefined);
  testEqual(t, `encodeJson None as null`, encodedJsonNone, null);
  let decodedSome = TopLevelOptions.maybeOptionRecord_decode(payloadJson);
  testEqual(t, `decode Some nested record`, decodedSome, {
    TAG: "Ok",
    _0: payload
  });
  let decodedNone = TopLevelOptions.maybeOptionRecord_decode(null);
  testEqual(t, `decode null`, decodedNone, {
    TAG: "Ok",
    _0: undefined
  });
});

Zora.test("top-level option alias in fixed JSON contexts", t => {
  let tupleEncoded = TopLevelOptions.mystringTuple_encode([
    "value",
    undefined
  ]);
  testEqual(t, `encode tuple alias None as null`, tupleEncoded, [
    "value",
    null
  ]);
  let variantEncoded = TopLevelOptions.mystringVariant_encode({
    TAG: "MystringVariant",
    _0: undefined
  });
  testEqual(t, `encode variant alias None as null`, variantEncoded, [
    "MystringVariant",
    null
  ]);
  let arrayEncoded = TopLevelOptions.mystringArray_encode([
    "value",
    undefined
  ]);
  testEqual(t, `encode array alias None as null`, arrayEncoded, [
    "value",
    null
  ]);
  let listEncoded = TopLevelOptions.mystringList_encode(Stdlib_List.fromArray([
    "value",
    undefined
  ]));
  testEqual(t, `encode list alias None as null`, listEncoded, [
    "value",
    null
  ]);
  let resultEncoded = TopLevelOptions.mystringResult_encode({
    TAG: "Ok",
    _0: undefined
  });
  testEqual(t, `encode result alias None as null`, resultEncoded, [
    "Ok",
    null
  ]);
});

Zora.test("nested record option contexts", t => {
  let encoded = TopLevelOptions.optionRecord_encode({
    title: "payload",
    optionalAlias: Primitive_option.some(undefined),
    aliases: [
      "alias",
      undefined
    ],
    tuple: [
      "tuple",
      undefined
    ],
    result: {
      TAG: "Error",
      _0: undefined
    }
  });
  testEqual(t, `encode record with nested option alias`, encoded, optionRecordJson());
  let decoded = TopLevelOptions.optionRecord_decode(optionRecordJson());
  testEqual(t, `decode record with nested option alias`, decoded, {
    TAG: "Ok",
    _0: {
      title: "payload",
      optionalAlias: Primitive_option.some(undefined),
      aliases: [
        "alias",
        undefined
      ],
      tuple: [
        "tuple",
        undefined
      ],
      result: {
        TAG: "Error",
        _0: undefined
      }
    }
  });
  let omittedRecord_aliases = [];
  let omittedRecord_tuple = [
    undefined,
    undefined
  ];
  let omittedRecord_result = {
    TAG: "Ok",
    _0: undefined
  };
  let omittedRecord = {
    title: "payload",
    optionalAlias: undefined,
    aliases: omittedRecord_aliases,
    tuple: omittedRecord_tuple,
    result: omittedRecord_result
  };
  let omittedJson = {
    title: "payload",
    aliases: [],
    tuple: [
      null,
      null
    ],
    result: [
      "Ok",
      null
    ]
  };
  let encodedOmitted = TopLevelOptions.optionRecord_encode(omittedRecord);
  testEqual(t, `encode omitted outer option field`, encodedOmitted, omittedJson);
  let decodedOmitted = TopLevelOptions.optionRecord_decode(omittedJson);
  testEqual(t, `decode missing outer option field`, decodedOmitted, {
    TAG: "Ok",
    _0: omittedRecord
  });
});

Zora.test("nested tuple, variant, and container option contexts", t => {
  let tupleEncoded = TopLevelOptions.nestedTuple_encode(nestedTuple());
  testEqual(t, `encode nested tuple`, tupleEncoded, nestedTupleJson());
  let tupleDecoded = TopLevelOptions.nestedTuple_decode(nestedTupleJson());
  testEqual(t, `decode nested tuple`, tupleDecoded, {
    TAG: "Ok",
    _0: nestedTuple()
  });
  let payloadVariant_2 = {
    title: "payload",
    optionalAlias: Primitive_option.some(undefined),
    aliases: [
      "alias",
      undefined
    ],
    tuple: [
      "tuple",
      undefined
    ],
    result: {
      TAG: "Error",
      _0: undefined
    }
  };
  let payloadVariant = {
    TAG: "Payload",
    _0: undefined,
    _1: undefined,
    _2: payloadVariant_2
  };
  let variantEncoded = TopLevelOptions.nestedVariant_encode(payloadVariant);
  testEqual(t, `encode nested variant payload`, variantEncoded, payloadVariantJson());
  let variantDecoded = TopLevelOptions.nestedVariant_decode(payloadVariantJson());
  testEqual(t, `decode nested variant payload`, variantDecoded, {
    TAG: "Ok",
    _0: payloadVariant
  });
  let maybeVariant = {
    TAG: "MaybePayload",
    _0: undefined
  };
  let maybeVariantJson = [
    "MaybePayload",
    null
  ];
  let maybeVariantEncoded = TopLevelOptions.nestedVariant_encode(maybeVariant);
  testEqual(t, `encode nested variant option alias`, maybeVariantEncoded, maybeVariantJson);
  let maybeVariantDecoded = TopLevelOptions.nestedVariant_decode(maybeVariantJson);
  testEqual(t, `decode nested variant option alias`, maybeVariantDecoded, {
    TAG: "Ok",
    _0: maybeVariant
  });
  let container_tuple = nestedTuple();
  let container_variants = [
    "Empty",
    maybeVariant,
    {
      TAG: "Payload",
      _0: "variant",
      _1: "plain",
      _2: {
        title: "payload",
        optionalAlias: Primitive_option.some(undefined),
        aliases: [
          "alias",
          undefined
        ],
        tuple: [
          "tuple",
          undefined
        ],
        result: {
          TAG: "Error",
          _0: undefined
        }
      }
    }
  ];
  let container_result = {
    TAG: "Ok",
    _0: undefined
  };
  let container = {
    maybePayload: undefined,
    variant: payloadVariant,
    tuple: container_tuple,
    variants: container_variants,
    result: container_result
  };
  let containerJson = {
    maybePayload: null,
    variant: payloadVariantJson(),
    tuple: nestedTupleJson(),
    variants: [
      ["Empty"],
      maybeVariantJson,
      [
        "Payload",
        "variant",
        "plain",
        optionRecordJson()
      ]
    ],
    result: [
      "Ok",
      null
    ]
  };
  let containerEncoded = TopLevelOptions.nestedContainer_encode(container);
  testEqual(t, `encode nested container`, containerEncoded, containerJson);
  let containerDecoded = TopLevelOptions.nestedContainer_decode(containerJson);
  testEqual(t, `decode nested container`, containerDecoded, {
    TAG: "Ok",
    _0: container
  });
});

export {
  testEqual,
  optionRecord,
  optionRecordJson,
  nestedTuple,
  nestedTupleJson,
  payloadVariantJson,
}
/*  Not a pure module */
