// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Tuples from "../../../src/Tuples.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("tuple with option", t => {
  let encodedSome = Tuples.withOption_encode([
    "name",
    "nickname"
  ]);
  testEqual(t, `encode Some`, encodedSome, [
    "name",
    "nickname"
  ]);
  let encodedNone = Tuples.withOption_encode([
    "name",
    undefined
  ]);
  testEqual(t, `encode None`, encodedNone, [
    "name",
    null
  ]);
  let decodedSome = Tuples.withOption_decode([
    "name",
    "nickname"
  ]);
  testEqual(t, `decode Some`, decodedSome, {
    TAG: "Ok",
    _0: [
      "name",
      "nickname"
    ]
  });
  let decodedNone = Tuples.withOption_decode([
    "name",
    null
  ]);
  testEqual(t, `decode None`, decodedNone, {
    TAG: "Ok",
    _0: [
      "name",
      undefined
    ]
  });
  let decodedInvalid = Tuples.withOption_decode([
    "name",
    1.0
  ]);
  t.test("decode invalid option payload includes tuple index", async t => {
    if (decodedInvalid.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    let match = decodedInvalid._0;
    t.equal(match.path, "[1]", "path");
    t.equal(match.message, "Not a string", "message");
    t.equal(match.value, 1.0, "value");
  });
});

export {
  testEqual,
}
/*  Not a pure module */
