// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Spice from "../../../src/Spice.mjs";
import * as Variants from "../../../src/Variants.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("variants with @spice.as", t => {
  let variantEncoded = Variants.t_encode("One");
  testEqual(t, `encode 하나`, variantEncoded, 1);
  let variantEncoded$1 = Variants.t_encode("Two");
  testEqual(t, `encode 둘`, variantEncoded$1, `둘`);
  let variantDecoded = Variants.t_decode(1);
  testEqual(t, `decode 하나`, variantDecoded, {
    TAG: "Ok",
    _0: "One"
  });
  let variantDecoded$1 = Variants.t_decode(`둘`);
  testEqual(t, `decode 둘`, variantDecoded$1, {
    TAG: "Ok",
    _0: "Two"
  });
});

Zora.test(`variants without @spice.as`, t => {
  let variantEncoded = Variants.t1_encode("One1");
  testEqual(t, `encode One1`, variantEncoded, [`One1`]);
  let variantEncoded$1 = Variants.t1_encode("Two1");
  testEqual(t, `encode Two1`, variantEncoded$1, [`Two1`]);
  let variantDecoded = Variants.t1_decode([`One1`]);
  testEqual(t, `decode ["One1"]`, variantDecoded, {
    TAG: "Ok",
    _0: "One1"
  });
  let variantDecoded$1 = Variants.t1_decode([`Two1`]);
  testEqual(t, `decode ["Two1"]`, variantDecoded$1, {
    TAG: "Ok",
    _0: "Two1"
  });
});

Zora.test("unboxed variants with @spice.as", t => {
  let variantEncoded = Variants.t2_encode(0);
  testEqual(t, `encode 하나`, variantEncoded, 0.0);
  let variantDecoded = Variants.t2_decode(0.0);
  testEqual(t, `decode 하나`, variantDecoded, {
    TAG: "Ok",
    _0: 0
  });
});

Zora.test(`unboxed variants without @spice.as`, t => {
  let variantEncoded = Variants.t3_encode(0);
  testEqual(t, `encode One3(0)`, variantEncoded, 0.0);
  let variantDecoded = Variants.t3_decode(0.0);
  testEqual(t, `decode 0`, variantDecoded, {
    TAG: "Ok",
    _0: 0
  });
});

Zora.test("variants with @spice.as number", t => {
  let variantEncoded = Variants.t4_encode("One");
  testEqual(t, `encode 1.0`, variantEncoded, 1.0);
  let variantEncoded$1 = Variants.t4_encode("Two");
  testEqual(t, `encode 2.0`, variantEncoded$1, 2.0);
  let variantDecoded = Variants.t4_decode(1.0);
  testEqual(t, `decode 1.0`, variantDecoded, {
    TAG: "Ok",
    _0: "One"
  });
  let variantDecoded$1 = Variants.t4_decode(2.0);
  testEqual(t, `decode 2.0`, variantDecoded$1, {
    TAG: "Ok",
    _0: "Two"
  });
});

Zora.test("variant payload with option", t => {
  let encodedSome = Variants.withOption_encode({
    TAG: "WithOption",
    _0: "value"
  });
  testEqual(t, `encode Some`, encodedSome, [
    "WithOption",
    "value"
  ]);
  let encoded = Variants.withOption_encode({
    TAG: "WithOption",
    _0: undefined
  });
  testEqual(t, `encode None`, encoded, [
    "WithOption",
    null
  ]);
  let decodedSome = Variants.withOption_decode([
    "WithOption",
    "value"
  ]);
  testEqual(t, `decode Some`, decodedSome, {
    TAG: "Ok",
    _0: {
      TAG: "WithOption",
      _0: "value"
    }
  });
  let decoded = Variants.withOption_decode([
    "WithOption",
    null
  ]);
  testEqual(t, `decode None`, decoded, {
    TAG: "Ok",
    _0: {
      TAG: "WithOption",
      _0: undefined
    }
  });
  let decodedInvalid = Variants.withOption_decode([
    "WithOption",
    1.0
  ]);
  t.test("decode invalid option payload includes variant payload index", async t => {
    if (decodedInvalid.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    let match = decodedInvalid._0;
    t.equal(match.path, "[1]", "path");
    t.equal(match.message, "Not a string", "message");
    t.equal(match.value, 1.0, "value");
  });
});

Zora.test("variant with payloadless and option payload constructors", t => {
  let encodedA = Variants.optionPayloadVariant_encode("A");
  testEqual(t, `encode A`, encodedA, ["A"]);
  let encodedSome = Variants.optionPayloadVariant_encode({
    TAG: "B",
    _0: "value"
  });
  testEqual(t, `encode B Some`, encodedSome, [
    "B",
    "value"
  ]);
  let encodedNone = Variants.optionPayloadVariant_encode({
    TAG: "B",
    _0: undefined
  });
  testEqual(t, `encode B None`, encodedNone, [
    "B",
    null
  ]);
  let decodedA = Variants.optionPayloadVariant_decode(["A"]);
  testEqual(t, `decode A`, decodedA, {
    TAG: "Ok",
    _0: "A"
  });
  let decodedSome = Variants.optionPayloadVariant_decode([
    "B",
    "value"
  ]);
  testEqual(t, `decode B Some`, decodedSome, {
    TAG: "Ok",
    _0: {
      TAG: "B",
      _0: "value"
    }
  });
  let decodedNone = Variants.optionPayloadVariant_decode([
    "B",
    null
  ]);
  testEqual(t, `decode B None`, decodedNone, {
    TAG: "Ok",
    _0: {
      TAG: "B",
      _0: undefined
    }
  });
  let decodedInvalid = Variants.optionPayloadVariant_decode([
    "B",
    1.0
  ]);
  t.test("decode invalid B option payload includes payload index", async t => {
    if (decodedInvalid.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    let match = decodedInvalid._0;
    t.equal(match.path, "[1]", "path");
    t.equal(match.message, "Not a string", "message");
    t.equal(match.value, 1.0, "value");
  });
});

Zora.test("variant with inline record payload", t => {
  let encodedBoo = Variants.inlineRecordPayload_encode({
    TAG: "InlineBoo",
    a: "Bo"
  });
  testEqual(t, `encode InlineBoo`, encodedBoo, [
    "InlineBoo",
    {
      a: "Bo"
    }
  ]);
  let decodedBoo = Variants.inlineRecordPayload_decode([
    "InlineBoo",
    {
      a: "Bo"
    }
  ]);
  testEqual(t, `decode InlineBoo`, decodedBoo, {
    TAG: "Ok",
    _0: {
      TAG: "InlineBoo",
      a: "Bo"
    }
  });
  let encodedBar = Variants.inlineRecordPayload_encode({
    TAG: "InlineBar",
    x: true
  });
  testEqual(t, `encode InlineBar`, encodedBar, [
    "InlineBar",
    {
      x: true
    }
  ]);
  let decodedBar = Variants.inlineRecordPayload_decode([
    "InlineBar",
    {
      x: true
    }
  ]);
  testEqual(t, `decode InlineBar`, decodedBar, {
    TAG: "Ok",
    _0: {
      TAG: "InlineBar",
      x: true
    }
  });
});

Zora.test("variant inline record payload field errors include payload index", t => {
  let decodedInvalid = Variants.inlineRecordPayload_decode([
    "InlineBoo",
    {
      a: 1.0
    }
  ]);
  t.test("decode invalid inline record field includes [1] path prefix", async t => {
    if (decodedInvalid.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    let match = decodedInvalid._0;
    t.equal(match.path, "[1].a", "path");
    t.equal(match.message, "Not a string", "message");
    t.equal(match.value, 1.0, "value");
  });
  let decodedMissing = Variants.inlineRecordPayload_decode([
    "InlineBoo",
    {}
  ]);
  t.test("decode missing inline record field includes [1] path prefix", async t => {
    if (decodedMissing.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    let match = decodedMissing._0;
    t.equal(match.path, "[1].a", "path");
    t.equal(match.message, "a missing", "message");
    t.equal(match.value, {}, "value");
  });
});

Zora.test("variant inline record payload optional fields", t => {
  let json = [
    "InlineOptional",
    {
      name: "payload"
    }
  ];
  let encoded = Variants.inlineRecordWithOptional_encode({
    TAG: "InlineOptional",
    name: "payload",
    maybe: undefined
  });
  testEqual(t, `encode omitted inline record option fields`, encoded, json);
  let decoded = Variants.inlineRecordWithOptional_decode(json);
  t.test("decode omitted inline record option fields", async t => {
    if (decoded.TAG === "Ok") {
      let match = decoded._0;
      t.equal(match.name, "payload", "name");
      t.equal(match.maybe, undefined, "maybe");
      t.equal(match.optional, undefined, "optional");
      return;
    }
    t.fail("expected decode to succeed");
  });
  let value = {
    TAG: "InlineOptional",
    name: "payload",
    maybe: "maybe",
    optional: "optional"
  };
  let json$1 = [
    "InlineOptional",
    {
      name: "payload",
      maybe: "maybe",
      optional: "optional"
    }
  ];
  let encoded$1 = Variants.inlineRecordWithOptional_encode(value);
  testEqual(t, `encode present inline record option fields`, encoded$1, json$1);
  let decoded$1 = Variants.inlineRecordWithOptional_decode(json$1);
  testEqual(t, `decode present inline record option fields`, decoded$1, {
    TAG: "Ok",
    _0: value
  });
});

Zora.test("variant inline record payload field attributes", t => {
  let value = {
    TAG: "InlineAttrs",
    id: "u1",
    name: "Ada"
  };
  let json = [
    "InlineAttrs",
    {
      user_id: "u1",
      name: "Ada"
    }
  ];
  let encoded = Variants.inlineRecordWithAttrs_encode(value);
  testEqual(t, `encode inline record @spice.key`, encoded, json);
  let decoded = Variants.inlineRecordWithAttrs_decode(json);
  testEqual(t, `decode inline record @spice.key`, decoded, {
    TAG: "Ok",
    _0: value
  });
  let defaultJson = [
    "InlineAttrs",
    {
      user_id: "u1"
    }
  ];
  let decodedDefault = Variants.inlineRecordWithAttrs_decode(defaultJson);
  testEqual(t, `decode inline record @spice.default`, decodedDefault, {
    TAG: "Ok",
    _0: {
      TAG: "InlineAttrs",
      id: "u1",
      name: "anonymous"
    }
  });
  let decodedInvalid = Variants.inlineRecordWithAttrs_decode([
    "InlineAttrs",
    {
      user_id: 1.0
    }
  ]);
  t.test("decode invalid keyed inline record field uses JSON key in path", async t => {
    if (decodedInvalid.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    let match = decodedInvalid._0;
    t.equal(match.path, "[1].user_id", "path");
    t.equal(match.message, "Not a string", "message");
    t.equal(match.value, 1.0, "value");
  });
});

Zora.test("variant inline record payload generic field", t => {
  let value = {
    TAG: "InlineGeneric",
    value: 42
  };
  let json = [
    "InlineGeneric",
    {
      value: 42.0
    }
  ];
  let encoded = Variants.inlineRecordGeneric_encode(Spice.intToJson)(value);
  testEqual(t, `encode generic inline record payload`, encoded, json);
  let decoded = Variants.inlineRecordGeneric_decode(Spice.intFromJson)(json);
  testEqual(t, `decode generic inline record payload`, decoded, {
    TAG: "Ok",
    _0: value
  });
});

Zora.test("unboxed variant with inline record payload", t => {
  let encoded = Variants.inlineRecordUnboxed_encode("Bo");
  testEqual(t, `encode unboxed inline record`, encoded, {
    a: "Bo"
  });
  let decoded = Variants.inlineRecordUnboxed_decode({
    a: "Bo"
  });
  testEqual(t, `decode unboxed inline record`, decoded, {
    TAG: "Ok",
    _0: "Bo"
  });
  let many = {
    a: "Bo",
    b: 1
  };
  let manyJson = {
    a: "Bo",
    b: 1.0
  };
  let encodedMany = Variants.inlineRecordUnboxedMany_encode(many);
  testEqual(t, `encode unboxed inline record with multiple fields`, encodedMany, manyJson);
  let decodedMany = Variants.inlineRecordUnboxedMany_decode(manyJson);
  testEqual(t, `decode unboxed inline record with multiple fields`, decodedMany, {
    TAG: "Ok",
    _0: many
  });
});

Zora.test("variant error path includes correct index", t => {
  let invalidJson = [
    "WithArgs",
    "not an int",
    "valid string"
  ];
  let decoded = Variants.withArgs_decode(invalidJson);
  t.test("error path shows [1] for first argument", async t => {
    if (decoded.TAG === "Ok") {
      t.fail("expected decode to fail");
      return;
    }
    t.equal(decoded._0.path, "[1]", "path should be [1]");
  });
});

export {
  testEqual,
}
/*  Not a pure module */
