// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function mystring_encode(v) {
  return Spice.optionToJson(Spice.stringToJson, v);
}

function mystring_encodeJson(v) {
  return Spice.optionToNullableJson(Spice.stringToJson, v);
}

function mystring_decode(v) {
  return Spice.optionFromJson(Spice.stringFromJson, v);
}

function mystringTuple_encode(v) {
  return [
    Spice.optionToNullableJson(Spice.stringToJson, v[0]),
    Spice.optionToNullableJson(Spice.stringToJson, v[1])
  ];
}

function mystringTuple_encodeJson(v) {
  return [
    Spice.optionToNullableJson(Spice.stringToJson, v[0]),
    Spice.optionToNullableJson(Spice.stringToJson, v[1])
  ];
}

function mystringTuple_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a tuple", v);
  }
  if (v.length !== 2) {
    return Spice.error(undefined, "Incorrect cardinality", v);
  }
  let v0 = v[0];
  let v1 = v[1];
  let match = Spice.optionFromJson(Spice.stringFromJson, v0);
  let match$1 = Spice.optionFromJson(Spice.stringFromJson, v1);
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: [
          match._0,
          match$1._0
        ]
      };
    }
    let e = match$1._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e.path,
        message: e.message,
        value: e.value
      }
    };
  }
  let e$1 = match._0;
  return {
    TAG: "Error",
    _0: {
      path: "[0]" + e$1.path,
      message: e$1.message,
      value: e$1.value
    }
  };
}

function mystringVariant_encode(v) {
  return [
    "MystringVariant",
    Spice.optionToNullableJson(Spice.stringToJson, v._0)
  ];
}

function mystringVariant_encodeJson(v) {
  return [
    "MystringVariant",
    Spice.optionToNullableJson(Spice.stringToJson, v._0)
  ];
}

function mystringVariant_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (match === "MystringVariant") {
    if (v.length !== 2) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    let v0 = Spice.optionFromJson(Spice.stringFromJson, v[1]);
    if (v0.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          TAG: "MystringVariant",
          _0: v0._0
        }
      };
    }
    let e = v0._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e.path,
        message: e.message,
        value: e.value
      }
    };
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function mystringArray_encode(v) {
  return Spice.arrayToJson(mystring_encodeJson, v);
}

function mystringArray_encodeJson(v) {
  return Spice.arrayToJson(mystring_encodeJson, v);
}

function mystringArray_decode(v) {
  return Spice.arrayFromJson(mystring_decode, v);
}

function mystringList_encode(v) {
  return Spice.listToJson(mystring_encodeJson, v);
}

function mystringList_encodeJson(v) {
  return Spice.listToJson(mystring_encodeJson, v);
}

function mystringList_decode(v) {
  return Spice.listFromJson(mystring_decode, v);
}

function mystringResult_encode(v) {
  return Spice.resultToJson(mystring_encodeJson, Spice.stringToJson, v);
}

function mystringResult_encodeJson(v) {
  return Spice.resultToJson(mystring_encodeJson, Spice.stringToJson, v);
}

function mystringResult_decode(v) {
  return Spice.resultFromJson(mystring_decode, Spice.stringFromJson, v);
}

function optionRecord_encode(v) {
  let param = v.tuple;
  let extra = v.result;
  return Object.fromEntries(Spice.filterOptional([
    [
      "title",
      Spice.stringToJson(v.title)
    ],
    [
      "optionalAlias",
      Spice.optionToJson(mystring_encodeJson, v.optionalAlias)
    ],
    [
      "aliases",
      Spice.arrayToJson(mystring_encodeJson, v.aliases)
    ],
    [
      "tuple",
      [
        Spice.optionToNullableJson(Spice.stringToJson, param[0]),
        Spice.optionToNullableJson(Spice.stringToJson, param[1])
      ]
    ],
    [
      "result",
      Spice.resultToJson(mystring_encodeJson, extra => Spice.optionToNullableJson(Spice.stringToJson, extra), extra)
    ]
  ]));
}

function optionRecord_encodeJson(v) {
  let param = v.tuple;
  let extra = v.result;
  return Object.fromEntries(Spice.filterOptional([
    [
      "title",
      Spice.stringToJson(v.title)
    ],
    [
      "optionalAlias",
      Spice.optionToJson(mystring_encodeJson, v.optionalAlias)
    ],
    [
      "aliases",
      Spice.arrayToJson(mystring_encodeJson, v.aliases)
    ],
    [
      "tuple",
      [
        Spice.optionToNullableJson(Spice.stringToJson, param[0]),
        Spice.optionToNullableJson(Spice.stringToJson, param[1])
      ]
    ],
    [
      "result",
      Spice.resultToJson(mystring_encodeJson, extra => Spice.optionToNullableJson(Spice.stringToJson, extra), extra)
    ]
  ]));
}

function optionRecord_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let title = Stdlib_Option.getOr(Stdlib_Option.map(v["title"], Spice.stringFromJson), Spice.error(undefined, "title" + " missing", v));
  if (title.TAG === "Ok") {
    let optionalAlias = Stdlib_Option.getOr(Stdlib_Option.map(v["optionalAlias"], json => Stdlib_Result.map(Spice.optionFromJson(Spice.stringFromJson, json), v => Primitive_option.some(v))), {
      TAG: "Ok",
      _0: undefined
    });
    if (optionalAlias.TAG === "Ok") {
      let aliases = Stdlib_Option.getOr(Stdlib_Option.map(v["aliases"], extra => Spice.arrayFromJson(mystring_decode, extra)), Spice.error(undefined, "aliases" + " missing", v));
      if (aliases.TAG === "Ok") {
        let tuple = Stdlib_Option.getOr(Stdlib_Option.map(v["tuple"], json => {
          if (!Array.isArray(json)) {
            return Spice.error(undefined, "Not a tuple", json);
          }
          if (json.length !== 2) {
            return Spice.error(undefined, "Incorrect cardinality", json);
          }
          let v0 = json[0];
          let v1 = json[1];
          let match = Spice.optionFromJson(Spice.stringFromJson, v0);
          let match$1 = Spice.optionFromJson(Spice.stringFromJson, v1);
          if (match.TAG === "Ok") {
            if (match$1.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: [
                  match._0,
                  match$1._0
                ]
              };
            }
            let e = match$1._0;
            return {
              TAG: "Error",
              _0: {
                path: "[1]" + e.path,
                message: e.message,
                value: e.value
              }
            };
          }
          let e$1 = match._0;
          return {
            TAG: "Error",
            _0: {
              path: "[0]" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
        }), Spice.error(undefined, "tuple" + " missing", v));
        if (tuple.TAG === "Ok") {
          let result = Stdlib_Option.getOr(Stdlib_Option.map(v["result"], extra => Spice.resultFromJson(mystring_decode, extra => Spice.optionFromJson(Spice.stringFromJson, extra), extra)), Spice.error(undefined, "result" + " missing", v));
          if (result.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                title: title._0,
                optionalAlias: optionalAlias._0,
                aliases: aliases._0,
                tuple: tuple._0,
                result: result._0
              }
            };
          }
          let e = result._0;
          return Spice.error("." + ("result" + e.path), e.message, e.value);
        }
        let e$1 = tuple._0;
        return Spice.error("." + ("tuple" + e$1.path), e$1.message, e$1.value);
      }
      let e$2 = aliases._0;
      return Spice.error("." + ("aliases" + e$2.path), e$2.message, e$2.value);
    }
    let e$3 = optionalAlias._0;
    return Spice.error("." + ("optionalAlias" + e$3.path), e$3.message, e$3.value);
  }
  let e$4 = title._0;
  return Spice.error("." + ("title" + e$4.path), e$4.message, e$4.value);
}

function maybeOptionRecord_encode(v) {
  return Spice.optionToJson(optionRecord_encodeJson, v);
}

function maybeOptionRecord_encodeJson(v) {
  return Spice.optionToNullableJson(optionRecord_encodeJson, v);
}

function maybeOptionRecord_decode(v) {
  return Spice.optionFromJson(optionRecord_decode, v);
}

function nestedTuple_encode(v) {
  return [
    Spice.optionToNullableJson(optionRecord_encodeJson, v[0]),
    optionRecord_encodeJson(v[1]),
    Spice.optionToNullableJson(Spice.stringToJson, v[2]),
    Spice.optionToNullableJson(Spice.stringToJson, v[3]),
    Spice.arrayToJson(mystring_encodeJson, v[4]),
    Spice.resultToJson(mystring_encodeJson, extra => Spice.optionToNullableJson(Spice.stringToJson, extra), v[5])
  ];
}

function nestedTuple_encodeJson(v) {
  return [
    Spice.optionToNullableJson(optionRecord_encodeJson, v[0]),
    optionRecord_encodeJson(v[1]),
    Spice.optionToNullableJson(Spice.stringToJson, v[2]),
    Spice.optionToNullableJson(Spice.stringToJson, v[3]),
    Spice.arrayToJson(mystring_encodeJson, v[4]),
    Spice.resultToJson(mystring_encodeJson, extra => Spice.optionToNullableJson(Spice.stringToJson, extra), v[5])
  ];
}

function nestedTuple_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a tuple", v);
  }
  if (v.length !== 6) {
    return Spice.error(undefined, "Incorrect cardinality", v);
  }
  let v0 = v[0];
  let v1 = v[1];
  let v2 = v[2];
  let v3 = v[3];
  let v4 = v[4];
  let v5 = v[5];
  let match = Spice.optionFromJson(optionRecord_decode, v0);
  let match$1 = optionRecord_decode(v1);
  let match$2 = Spice.optionFromJson(Spice.stringFromJson, v2);
  let match$3 = Spice.optionFromJson(Spice.stringFromJson, v3);
  let match$4 = Spice.arrayFromJson(mystring_decode, v4);
  let match$5 = Spice.resultFromJson(mystring_decode, extra => Spice.optionFromJson(Spice.stringFromJson, extra), v5);
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      if (match$2.TAG === "Ok") {
        if (match$3.TAG === "Ok") {
          if (match$4.TAG === "Ok") {
            if (match$5.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: [
                  match._0,
                  match$1._0,
                  match$2._0,
                  match$3._0,
                  match$4._0,
                  match$5._0
                ]
              };
            }
            let e = match$5._0;
            return {
              TAG: "Error",
              _0: {
                path: "[5]" + e.path,
                message: e.message,
                value: e.value
              }
            };
          }
          let e$1 = match$4._0;
          return {
            TAG: "Error",
            _0: {
              path: "[4]" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
        }
        let e$2 = match$3._0;
        return {
          TAG: "Error",
          _0: {
            path: "[3]" + e$2.path,
            message: e$2.message,
            value: e$2.value
          }
        };
      }
      let e$3 = match$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[2]" + e$3.path,
          message: e$3.message,
          value: e$3.value
        }
      };
    }
    let e$4 = match$1._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e$4.path,
        message: e$4.message,
        value: e$4.value
      }
    };
  }
  let e$5 = match._0;
  return {
    TAG: "Error",
    _0: {
      path: "[0]" + e$5.path,
      message: e$5.message,
      value: e$5.value
    }
  };
}

function nestedVariant_encode(v) {
  if (typeof v !== "object") {
    return ["Empty"];
  } else if (v.TAG === "Payload") {
    return [
      "Payload",
      Spice.optionToNullableJson(Spice.stringToJson, v._0),
      Spice.optionToNullableJson(Spice.stringToJson, v._1),
      optionRecord_encodeJson(v._2)
    ];
  } else {
    return [
      "MaybePayload",
      Spice.optionToNullableJson(optionRecord_encodeJson, v._0)
    ];
  }
}

function nestedVariant_encodeJson(v) {
  if (typeof v !== "object") {
    return ["Empty"];
  } else if (v.TAG === "Payload") {
    return [
      "Payload",
      Spice.optionToNullableJson(Spice.stringToJson, v._0),
      Spice.optionToNullableJson(Spice.stringToJson, v._1),
      optionRecord_encodeJson(v._2)
    ];
  } else {
    return [
      "MaybePayload",
      Spice.optionToNullableJson(optionRecord_encodeJson, v._0)
    ];
  }
}

function nestedVariant_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "Empty" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "Empty"
          };
        }
      case "MaybePayload" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v0 = Spice.optionFromJson(optionRecord_decode, v[1]);
        if (v0.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "MaybePayload",
              _0: v0._0
            }
          };
        }
        let e = v0._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e.path,
            message: e.message,
            value: e.value
          }
        };
      case "Payload" :
        if (v.length !== 4) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let match$1 = Spice.optionFromJson(Spice.stringFromJson, v[1]);
        let extra = v[2];
        let match$2 = Spice.optionFromJson(Spice.stringFromJson, extra);
        let match$3 = optionRecord_decode(v[3]);
        if (match$1.TAG === "Ok") {
          if (match$2.TAG === "Ok") {
            if (match$3.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  TAG: "Payload",
                  _0: match$1._0,
                  _1: match$2._0,
                  _2: match$3._0
                }
              };
            }
            let e$1 = match$3._0;
            return {
              TAG: "Error",
              _0: {
                path: "[3]" + e$1.path,
                message: e$1.message,
                value: e$1.value
              }
            };
          }
          let e$2 = match$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[2]" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
        }
        let e$3 = match$1._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function nestedContainer_encode(v) {
  let extra = v.result;
  return Object.fromEntries(Spice.filterOptional([
    [
      "maybePayload",
      Spice.optionToNullableJson(optionRecord_encodeJson, v.maybePayload)
    ],
    [
      "variant",
      nestedVariant_encodeJson(v.variant)
    ],
    [
      "tuple",
      nestedTuple_encodeJson(v.tuple)
    ],
    [
      "variants",
      Spice.arrayToJson(nestedVariant_encodeJson, v.variants)
    ],
    [
      "result",
      Spice.resultToJson(maybeOptionRecord_encodeJson, extra => Spice.optionToNullableJson(Spice.stringToJson, extra), extra)
    ]
  ]));
}

function nestedContainer_encodeJson(v) {
  let extra = v.result;
  return Object.fromEntries(Spice.filterOptional([
    [
      "maybePayload",
      Spice.optionToNullableJson(optionRecord_encodeJson, v.maybePayload)
    ],
    [
      "variant",
      nestedVariant_encodeJson(v.variant)
    ],
    [
      "tuple",
      nestedTuple_encodeJson(v.tuple)
    ],
    [
      "variants",
      Spice.arrayToJson(nestedVariant_encodeJson, v.variants)
    ],
    [
      "result",
      Spice.resultToJson(maybeOptionRecord_encodeJson, extra => Spice.optionToNullableJson(Spice.stringToJson, extra), extra)
    ]
  ]));
}

function nestedContainer_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let maybePayload = Stdlib_Option.getOr(Stdlib_Option.map(v["maybePayload"], maybeOptionRecord_decode), Spice.error(undefined, "maybePayload" + " missing", v));
  if (maybePayload.TAG === "Ok") {
    let variant = Stdlib_Option.getOr(Stdlib_Option.map(v["variant"], nestedVariant_decode), Spice.error(undefined, "variant" + " missing", v));
    if (variant.TAG === "Ok") {
      let tuple = Stdlib_Option.getOr(Stdlib_Option.map(v["tuple"], nestedTuple_decode), Spice.error(undefined, "tuple" + " missing", v));
      if (tuple.TAG === "Ok") {
        let variants = Stdlib_Option.getOr(Stdlib_Option.map(v["variants"], extra => Spice.arrayFromJson(nestedVariant_decode, extra)), Spice.error(undefined, "variants" + " missing", v));
        if (variants.TAG === "Ok") {
          let result = Stdlib_Option.getOr(Stdlib_Option.map(v["result"], extra => Spice.resultFromJson(maybeOptionRecord_decode, extra => Spice.optionFromJson(Spice.stringFromJson, extra), extra)), Spice.error(undefined, "result" + " missing", v));
          if (result.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                maybePayload: maybePayload._0,
                variant: variant._0,
                tuple: tuple._0,
                variants: variants._0,
                result: result._0
              }
            };
          }
          let e = result._0;
          return Spice.error("." + ("result" + e.path), e.message, e.value);
        }
        let e$1 = variants._0;
        return Spice.error("." + ("variants" + e$1.path), e$1.message, e$1.value);
      }
      let e$2 = tuple._0;
      return Spice.error("." + ("tuple" + e$2.path), e$2.message, e$2.value);
    }
    let e$3 = variant._0;
    return Spice.error("." + ("variant" + e$3.path), e$3.message, e$3.value);
  }
  let e$4 = maybePayload._0;
  return Spice.error("." + ("maybePayload" + e$4.path), e$4.message, e$4.value);
}

export {
  mystring_encode,
  mystring_encodeJson,
  mystring_decode,
  mystringTuple_encode,
  mystringTuple_encodeJson,
  mystringTuple_decode,
  mystringVariant_encode,
  mystringVariant_encodeJson,
  mystringVariant_decode,
  mystringArray_encode,
  mystringArray_encodeJson,
  mystringArray_decode,
  mystringList_encode,
  mystringList_encodeJson,
  mystringList_decode,
  mystringResult_encode,
  mystringResult_encodeJson,
  mystringResult_decode,
  optionRecord_encode,
  optionRecord_encodeJson,
  optionRecord_decode,
  maybeOptionRecord_encode,
  maybeOptionRecord_encodeJson,
  maybeOptionRecord_decode,
  nestedTuple_encode,
  nestedTuple_encodeJson,
  nestedTuple_decode,
  nestedVariant_encode,
  nestedVariant_encodeJson,
  nestedVariant_decode,
  nestedContainer_encode,
  nestedContainer_encodeJson,
  nestedContainer_decode,
}
/* No side effect */
