// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function t_encode(v) {
  if (v === "One") {
    return 1;
  } else {
    return "둘";
  }
}

function t_encodeJson(v) {
  if (v === "One") {
    return 1;
  } else {
    return "둘";
  }
}

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("둘" === v) {
        return {
          TAG: "Ok",
          _0: "Two"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      if (1 === v) {
        return {
          TAG: "Ok",
          _0: "One"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function t1_encode(v) {
  if (v === "One1") {
    return ["One1"];
  } else {
    return ["Two1"];
  }
}

function t1_encodeJson(v) {
  if (v === "One1") {
    return ["One1"];
  } else {
    return ["Two1"];
  }
}

function t1_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "One1" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "One1"
          };
        }
      case "Two1" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "Two1"
          };
        }
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

let t2_encode = Spice.intToJson;

let t2_encodeJson = Spice.intToJson;

function t2_decode(v) {
  return Stdlib_Result.map(Spice.intFromJson(v), v => v);
}

let t3_encode = Spice.intToJson;

let t3_encodeJson = Spice.intToJson;

function t3_decode(v) {
  return Stdlib_Result.map(Spice.intFromJson(v), v => v);
}

function t4_encode(v) {
  if (v === "One") {
    return 1.0;
  } else {
    return 2.0;
  }
}

function t4_encodeJson(v) {
  if (v === "One") {
    return 1.0;
  } else {
    return 2.0;
  }
}

function t4_decode(v) {
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Not matched", v);
    case "number" :
      if (1.0 === v) {
        return {
          TAG: "Ok",
          _0: "One"
        };
      } else if (2.0 === v) {
        return {
          TAG: "Ok",
          _0: "Two"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function withOption_encode(v) {
  return [
    "WithOption",
    Spice.optionToNullableJson(Spice.stringToJson, v._0)
  ];
}

function withOption_encodeJson(v) {
  return [
    "WithOption",
    Spice.optionToNullableJson(Spice.stringToJson, v._0)
  ];
}

function withOption_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (match === "WithOption") {
    if (v.length !== 2) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    let extra = v[1];
    let v0 = Spice.optionFromJson(Spice.stringFromJson, extra);
    if (v0.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          TAG: "WithOption",
          _0: v0._0
        }
      };
    }
    let e = v0._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e.path,
        message: e.message,
        value: e.value
      }
    };
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function optionPayloadVariant_encode(v) {
  if (typeof v !== "object") {
    return ["A"];
  } else {
    return [
      "B",
      Spice.optionToNullableJson(Spice.stringToJson, v._0)
    ];
  }
}

function optionPayloadVariant_encodeJson(v) {
  if (typeof v !== "object") {
    return ["A"];
  } else {
    return [
      "B",
      Spice.optionToNullableJson(Spice.stringToJson, v._0)
    ];
  }
}

function optionPayloadVariant_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "A" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "A"
          };
        }
      case "B" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let extra = v[1];
        let v0 = Spice.optionFromJson(Spice.stringFromJson, extra);
        if (v0.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "B",
              _0: v0._0
            }
          };
        }
        let e = v0._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e.path,
            message: e.message,
            value: e.value
          }
        };
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function inlineRecordPayload_encode(v) {
  if (v.TAG === "InlineBoo") {
    return [
      "InlineBoo",
      Object.fromEntries(Spice.filterOptional([[
          "a",
          Spice.stringToJson(v.a)
        ]]))
    ];
  } else {
    return [
      "InlineBar",
      Object.fromEntries(Spice.filterOptional([[
          "x",
          Spice.boolToJson(v.x)
        ]]))
    ];
  }
}

function inlineRecordPayload_encodeJson(v) {
  if (v.TAG === "InlineBoo") {
    return [
      "InlineBoo",
      Object.fromEntries(Spice.filterOptional([[
          "a",
          Spice.stringToJson(v.a)
        ]]))
    ];
  } else {
    return [
      "InlineBar",
      Object.fromEntries(Spice.filterOptional([[
          "x",
          Spice.boolToJson(v.x)
        ]]))
    ];
  }
}

function inlineRecordPayload_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "InlineBar" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v$1 = v[1];
        let v$2;
        if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
          let x = Stdlib_Option.getOr(Stdlib_Option.map(v$1["x"], Spice.boolFromJson), Spice.error(undefined, "x" + " missing", v$1));
          if (x.TAG === "Ok") {
            v$2 = {
              TAG: "Ok",
              _0: {
                TAG: "InlineBar",
                x: x._0
              }
            };
          } else {
            let e = x._0;
            v$2 = Spice.error("." + ("x" + e.path), e.message, e.value);
          }
        } else {
          v$2 = Spice.error(undefined, "Not an object", v$1);
        }
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$1 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
      case "InlineBoo" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v$3 = v[1];
        let v$4;
        if (typeof v$3 === "object" && v$3 !== null && !Array.isArray(v$3)) {
          let a = Stdlib_Option.getOr(Stdlib_Option.map(v$3["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v$3));
          if (a.TAG === "Ok") {
            v$4 = {
              TAG: "Ok",
              _0: {
                TAG: "InlineBoo",
                a: a._0
              }
            };
          } else {
            let e$2 = a._0;
            v$4 = Spice.error("." + ("a" + e$2.path), e$2.message, e$2.value);
          }
        } else {
          v$4 = Spice.error(undefined, "Not an object", v$3);
        }
        if (v$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$4._0
          };
        }
        let e$3 = v$4._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function inlineRecordWithOptional_encode(v) {
  return [
    "InlineOptional",
    Object.fromEntries(Spice.filterOptional([
      [
        "name",
        Spice.stringToJson(v.name)
      ],
      [
        "maybe",
        Spice.optionToJson(Spice.stringToJson, v.maybe)
      ],
      [
        "optional",
        Spice.optionToJson(Spice.stringToJson, v.optional)
      ]
    ]))
  ];
}

function inlineRecordWithOptional_encodeJson(v) {
  return [
    "InlineOptional",
    Object.fromEntries(Spice.filterOptional([
      [
        "name",
        Spice.stringToJson(v.name)
      ],
      [
        "maybe",
        Spice.optionToJson(Spice.stringToJson, v.maybe)
      ],
      [
        "optional",
        Spice.optionToJson(Spice.stringToJson, v.optional)
      ]
    ]))
  ];
}

function inlineRecordWithOptional_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (match === "InlineOptional") {
    if (v.length !== 2) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    let v$1 = v[1];
    let v$2;
    if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
      let name = Stdlib_Option.getOr(Stdlib_Option.map(v$1["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v$1));
      if (name.TAG === "Ok") {
        let maybe = Stdlib_Option.getOr(Stdlib_Option.map(v$1["maybe"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (maybe.TAG === "Ok") {
          let optional = Stdlib_Option.getOr(Stdlib_Option.map(v$1["optional"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
            TAG: "Ok",
            _0: undefined
          });
          if (optional.TAG === "Ok") {
            v$2 = {
              TAG: "Ok",
              _0: {
                TAG: "InlineOptional",
                name: name._0,
                maybe: maybe._0,
                optional: optional._0
              }
            };
          } else {
            let e = optional._0;
            v$2 = Spice.error("." + ("optional" + e.path), e.message, e.value);
          }
        } else {
          let e$1 = maybe._0;
          v$2 = Spice.error("." + ("maybe" + e$1.path), e$1.message, e$1.value);
        }
      } else {
        let e$2 = name._0;
        v$2 = Spice.error("." + ("name" + e$2.path), e$2.message, e$2.value);
      }
    } else {
      v$2 = Spice.error(undefined, "Not an object", v$1);
    }
    if (v$2.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: v$2._0
      };
    }
    let e$3 = v$2._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e$3.path,
        message: e$3.message,
        value: e$3.value
      }
    };
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function inlineRecordWithAttrs_encode(v) {
  return [
    "InlineAttrs",
    Object.fromEntries(Spice.filterOptional([
      [
        "user_id",
        Spice.stringToJson(v.id)
      ],
      [
        "name",
        Spice.stringToJson(v.name)
      ]
    ]))
  ];
}

function inlineRecordWithAttrs_encodeJson(v) {
  return [
    "InlineAttrs",
    Object.fromEntries(Spice.filterOptional([
      [
        "user_id",
        Spice.stringToJson(v.id)
      ],
      [
        "name",
        Spice.stringToJson(v.name)
      ]
    ]))
  ];
}

function inlineRecordWithAttrs_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (match === "InlineAttrs") {
    if (v.length !== 2) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    let v$1 = v[1];
    let v$2;
    if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
      let id = Stdlib_Option.getOr(Stdlib_Option.map(v$1["user_id"], Spice.stringFromJson), Spice.error(undefined, "user_id" + " missing", v$1));
      if (id.TAG === "Ok") {
        let name = Stdlib_Option.getOr(Stdlib_Option.map(v$1["name"], Spice.stringFromJson), {
          TAG: "Ok",
          _0: "anonymous"
        });
        if (name.TAG === "Ok") {
          v$2 = {
            TAG: "Ok",
            _0: {
              TAG: "InlineAttrs",
              id: id._0,
              name: name._0
            }
          };
        } else {
          let e = name._0;
          v$2 = Spice.error("." + ("name" + e.path), e.message, e.value);
        }
      } else {
        let e$1 = id._0;
        v$2 = Spice.error("." + ("user_id" + e$1.path), e$1.message, e$1.value);
      }
    } else {
      v$2 = Spice.error(undefined, "Not an object", v$1);
    }
    if (v$2.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: v$2._0
      };
    }
    let e$2 = v$2._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e$2.path,
        message: e$2.message,
        value: e$2.value
      }
    };
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function inlineRecordGeneric_encode(encoder_a) {
  return v => ([
    "InlineGeneric",
    Object.fromEntries(Spice.filterOptional([[
        "value",
        encoder_a(v.value)
      ]]))
  ]);
}

function inlineRecordGeneric_encodeJson(encoder_a) {
  return v => ([
    "InlineGeneric",
    Object.fromEntries(Spice.filterOptional([[
        "value",
        encoder_a(v.value)
      ]]))
  ]);
}

function inlineRecordGeneric_decode(decoder_a) {
  return v => {
    if (!Array.isArray(v)) {
      return Spice.error(undefined, "Not a variant", v);
    }
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "InlineGeneric") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let value = Stdlib_Option.getOr(Stdlib_Option.map(v$1["value"], decoder_a), Spice.error(undefined, "value" + " missing", v$1));
        if (value.TAG === "Ok") {
          v$2 = {
            TAG: "Ok",
            _0: {
              TAG: "InlineGeneric",
              value: value._0
            }
          };
        } else {
          let e = value._0;
          v$2 = Spice.error("." + ("value" + e.path), e.message, e.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$1 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$1.path,
          message: e$1.message,
          value: e$1.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  };
}

function inlineRecordUnboxed_encode(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "a",
      Spice.stringToJson(v)
    ]]));
}

function inlineRecordUnboxed_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "a",
      Spice.stringToJson(v)
    ]]));
}

function inlineRecordUnboxed_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let a = Stdlib_Option.getOr(Stdlib_Option.map(v["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v));
  if (a.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: a._0
    };
  }
  let e = a._0;
  return Spice.error("." + ("a" + e.path), e.message, e.value);
}

function inlineRecordUnboxedMany_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "a",
      Spice.stringToJson(v.a)
    ],
    [
      "b",
      Spice.intToJson(v.b)
    ]
  ]));
}

function inlineRecordUnboxedMany_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "a",
      Spice.stringToJson(v.a)
    ],
    [
      "b",
      Spice.intToJson(v.b)
    ]
  ]));
}

function inlineRecordUnboxedMany_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let a = Stdlib_Option.getOr(Stdlib_Option.map(v["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v));
  if (a.TAG === "Ok") {
    let b = Stdlib_Option.getOr(Stdlib_Option.map(v["b"], Spice.intFromJson), Spice.error(undefined, "b" + " missing", v));
    if (b.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          a: a._0,
          b: b._0
        }
      };
    }
    let e = b._0;
    return Spice.error("." + ("b" + e.path), e.message, e.value);
  }
  let e$1 = a._0;
  return Spice.error("." + ("a" + e$1.path), e$1.message, e$1.value);
}

function withArgs_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (match === "WithArgs") {
    if (v.length !== 3) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    let match$1 = Spice.intFromJson(v[1]);
    let match$2 = Spice.stringFromJson(v[2]);
    if (match$1.TAG === "Ok") {
      if (match$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "WithArgs",
            _0: match$1._0,
            _1: match$2._0
          }
        };
      }
      let e = match$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[2]" + e.path,
          message: e.message,
          value: e.value
        }
      };
    }
    let e$1 = match$1._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e$1.path,
        message: e$1.message,
        value: e$1.value
      }
    };
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

export {
  t_encode,
  t_encodeJson,
  t_decode,
  t1_encode,
  t1_encodeJson,
  t1_decode,
  t2_encode,
  t2_encodeJson,
  t2_decode,
  t3_encode,
  t3_encodeJson,
  t3_decode,
  t4_encode,
  t4_encodeJson,
  t4_decode,
  withOption_encode,
  withOption_encodeJson,
  withOption_decode,
  optionPayloadVariant_encode,
  optionPayloadVariant_encodeJson,
  optionPayloadVariant_decode,
  inlineRecordPayload_encode,
  inlineRecordPayload_encodeJson,
  inlineRecordPayload_decode,
  inlineRecordWithOptional_encode,
  inlineRecordWithOptional_encodeJson,
  inlineRecordWithOptional_decode,
  inlineRecordWithAttrs_encode,
  inlineRecordWithAttrs_encodeJson,
  inlineRecordWithAttrs_decode,
  inlineRecordGeneric_encode,
  inlineRecordGeneric_encodeJson,
  inlineRecordGeneric_decode,
  inlineRecordUnboxed_encode,
  inlineRecordUnboxed_encodeJson,
  inlineRecordUnboxed_decode,
  inlineRecordUnboxedMany_encode,
  inlineRecordUnboxedMany_encodeJson,
  inlineRecordUnboxedMany_decode,
  withArgs_decode,
}
/* No side effect */
