// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function language_encode(v) {
  return "ReScript";
}

function language_encodeJson(v) {
  return "ReScript";
}

function language_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("ReScript" === v) {
        return {
          TAG: "Ok",
          _0: "ReScript"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function profile_encode(v) {
  let extra = v.languages;
  return Object.fromEntries(Spice.filterOptional([[
      "languages",
      Spice.optionToJson(extra => Spice.arrayToJson(language_encodeJson, extra), extra)
    ]]));
}

function profile_encodeJson(v) {
  let extra = v.languages;
  return Object.fromEntries(Spice.filterOptional([[
      "languages",
      Spice.optionToJson(extra => Spice.arrayToJson(language_encodeJson, extra), extra)
    ]]));
}

function profile_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let languages = Stdlib_Option.getOr(Stdlib_Option.map(v["languages"], json => Stdlib_Result.map(Spice.arrayFromJson(language_decode, json), v => v)), {
    TAG: "Ok",
    _0: undefined
  });
  if (languages.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        languages: languages._0
      }
    };
  }
  let e = languages._0;
  return Spice.error("." + ("languages" + e.path), e.message, e.value);
}

function user_encode(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "profile",
      profile_encodeJson(v.profile)
    ]]));
}

function user_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "profile",
      profile_encodeJson(v.profile)
    ]]));
}

function user_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let profile = Stdlib_Option.getOr(Stdlib_Option.map(v["profile"], profile_decode), Spice.error(undefined, "profile" + " missing", v));
  if (profile.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        profile: profile._0
      }
    };
  }
  let e = profile._0;
  return Spice.error("." + ("profile" + e.path), e.message, e.value);
}

export {
  language_encode,
  language_encodeJson,
  language_decode,
  profile_encode,
  profile_encodeJson,
  profile_decode,
  user_encode,
  user_encodeJson,
  user_decode,
}
/* No side effect */
