// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function things_encode(v) {
  if (v.TAG === "Boo") {
    return [
      "Boo",
      Object.fromEntries(Spice.filterOptional([[
          "a",
          Spice.stringToJson(v.a)
        ]]))
    ];
  } else {
    return [
      "Bar",
      Object.fromEntries(Spice.filterOptional([[
          "x",
          Spice.boolToJson(v.x)
        ]]))
    ];
  }
}

function things_encodeJson(v) {
  if (v.TAG === "Boo") {
    return [
      "Boo",
      Object.fromEntries(Spice.filterOptional([[
          "a",
          Spice.stringToJson(v.a)
        ]]))
    ];
  } else {
    return [
      "Bar",
      Object.fromEntries(Spice.filterOptional([[
          "x",
          Spice.boolToJson(v.x)
        ]]))
    ];
  }
}

function things_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "Bar" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v$1 = v[1];
        let v$2;
        if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
          let x = Stdlib_Option.getOr(Stdlib_Option.map(v$1["x"], Spice.boolFromJson), Spice.error(undefined, "x" + " missing", v$1));
          if (x.TAG === "Ok") {
            v$2 = {
              TAG: "Ok",
              _0: {
                TAG: "Bar",
                x: x._0
              }
            };
          } else {
            let e = x._0;
            v$2 = Spice.error("." + ("x" + e.path), e.message, e.value);
          }
        } else {
          v$2 = Spice.error(undefined, "Not an object", v$1);
        }
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$1 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
      case "Boo" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v$3 = v[1];
        let v$4;
        if (typeof v$3 === "object" && v$3 !== null && !Array.isArray(v$3)) {
          let a = Stdlib_Option.getOr(Stdlib_Option.map(v$3["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v$3));
          if (a.TAG === "Ok") {
            v$4 = {
              TAG: "Ok",
              _0: {
                TAG: "Boo",
                a: a._0
              }
            };
          } else {
            let e$2 = a._0;
            v$4 = Spice.error("." + ("a" + e$2.path), e$2.message, e$2.value);
          }
        } else {
          v$4 = Spice.error(undefined, "Not an object", v$3);
        }
        if (v$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$4._0
          };
        }
        let e$3 = v$4._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

let x = {
  TAG: "Boo",
  a: "Bo"
};

export {
  things_encode,
  things_encodeJson,
  things_decode,
  x,
}
/* No side effect */
