// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Spice = require("@mununki/ppx-spice/src/rescript/Spice.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Stdlib_Result = require("@rescript/runtime/lib/js/Stdlib_Result.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

function profile_encode(v) {
  let extra = v.nickname;
  let extra$1 = v.middleName;
  let extra$2 = v.title;
  return Object.fromEntries(Spice.filterOptional([
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "nickname",
      Spice.optionalToJson(Spice.stringToJson, extra)
    ],
    [
      "middleName",
      Spice.optionalToJson(extra => Spice.nullToJson(Spice.stringToJson, extra), extra$1)
    ],
    [
      "title",
      Spice.optionalToJson(Spice.stringToJson, extra$2)
    ]
  ]));
}

function profile_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
  if (name.TAG === "Ok") {
    let nickname = Stdlib_Option.getOr(Stdlib_Option.map(v["nickname"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
      TAG: "Ok",
      _0: undefined
    });
    if (nickname.TAG === "Ok") {
      let middleName = Stdlib_Option.getOr(Stdlib_Option.map(v["middleName"], json => Stdlib_Result.map(Spice.nullFromJson(Spice.stringFromJson, json), v => Primitive_option.some(v))), {
        TAG: "Ok",
        _0: undefined
      });
      if (middleName.TAG === "Ok") {
        let title = Stdlib_Option.getOr(Stdlib_Option.map(v["title"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (title.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              name: name._0,
              nickname: nickname._0,
              middleName: middleName._0,
              title: title._0
            }
          };
        }
        let e = title._0;
        return Spice.error("." + ("title" + e.path), e.message, e.value);
      }
      let e$1 = middleName._0;
      return Spice.error("." + ("middleName" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = nickname._0;
    return Spice.error("." + ("nickname" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = name._0;
  return Spice.error("." + ("name" + e$3.path), e$3.message, e$3.value);
}

function nameParts_encode(v) {
  return [
    Spice.stringToJson(v[0]),
    Spice.optionToJson(Spice.stringToJson, v[1])
  ];
}

function nameParts_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a tuple", v);
  }
  if (v.length !== 2) {
    return Spice.error(undefined, "Incorrect cardinality", v);
  }
  let v0 = v[0];
  let v1 = v[1];
  let match = Spice.stringFromJson(v0);
  let match$1 = Spice.optionFromJson(Spice.stringFromJson, v1);
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: [
          match._0,
          match$1._0
        ]
      };
    }
    let e = match$1._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e.path,
        message: e.message,
        value: e.value
      }
    };
  }
  let e$1 = match._0;
  return {
    TAG: "Error",
    _0: {
      path: "[0]" + e$1.path,
      message: e$1.message,
      value: e$1.value
    }
  };
}

function event_encode(v) {
  return [
    "Renamed",
    Spice.optionToJson(Spice.stringToJson, v._0)
  ];
}

function event_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (match === "Renamed") {
    if (v.length !== 2) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    let extra = v[1];
    let v0 = Spice.optionFromJson(Spice.stringFromJson, extra);
    if (v0.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          TAG: "Renamed",
          _0: v0._0
        }
      };
    }
    let e = v0._0;
    return {
      TAG: "Error",
      _0: {
        path: "[1]" + e.path,
        message: e.message,
        value: e.value
      }
    };
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

let profileWithoutOptionalValues = {
  name: "Alice",
  nickname: undefined,
  middleName: undefined
};

let profileWithoutOptionalValuesJson = profile_encode(profileWithoutOptionalValues);

let profileWithJsonNull = {
  name: "Alice",
  nickname: undefined,
  middleName: null
};

let profileWithJsonNullJson = profile_encode(profileWithJsonNull);

let missingRecordFields = {
    "name": "Alice"
  };

let missingRecordFieldsResult = profile_decode(missingRecordFields);

let presentNullRecordField = {
    "name": "Alice",
    "nickname": null
  };

let presentNullRecordFieldError = profile_decode(presentNullRecordField);

let tupleWithNone = [
  "Alice",
  undefined
];

let tupleWithNoneJson = nameParts_encode(tupleWithNone);

let tupleNullPayload = ["Alice", null];

let tupleNullPayloadResult = nameParts_decode(tupleNullPayload);

let eventWithNone = {
  TAG: "Renamed",
  _0: undefined
};

let eventWithNoneJson = event_encode(eventWithNone);

let eventNullPayload = ["Renamed", null];

let eventNullPayloadResult = event_decode(eventNullPayload);

exports.profile_encode = profile_encode;
exports.profile_decode = profile_decode;
exports.nameParts_encode = nameParts_encode;
exports.nameParts_decode = nameParts_decode;
exports.event_encode = event_encode;
exports.event_decode = event_decode;
exports.profileWithoutOptionalValues = profileWithoutOptionalValues;
exports.profileWithoutOptionalValuesJson = profileWithoutOptionalValuesJson;
exports.profileWithJsonNull = profileWithJsonNull;
exports.profileWithJsonNullJson = profileWithJsonNullJson;
exports.missingRecordFields = missingRecordFields;
exports.missingRecordFieldsResult = missingRecordFieldsResult;
exports.presentNullRecordField = presentNullRecordField;
exports.presentNullRecordFieldError = presentNullRecordFieldError;
exports.tupleWithNone = tupleWithNone;
exports.tupleWithNoneJson = tupleWithNoneJson;
exports.tupleNullPayload = tupleNullPayload;
exports.tupleNullPayloadResult = tupleNullPayloadResult;
exports.eventWithNone = eventWithNone;
exports.eventWithNoneJson = eventWithNoneJson;
exports.eventNullPayload = eventNullPayload;
exports.eventNullPayloadResult = eventNullPayloadResult;
/* profileWithoutOptionalValuesJson Not a pure module */
