// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function mystring0_encode(v) {
  return Spice.optionToJson(Spice.stringToJson, v);
}

function mystring0_encodeJson(v) {
  return Spice.optionToNullableJson(Spice.stringToJson, v);
}

function mystring0_decode(v) {
  return Spice.optionFromJson(Spice.stringFromJson, v);
}

function encoding0(str) {
  return Spice.optionToJson(Spice.stringToJson, str);
}

function mystring1_encode(v) {
  let extra = v.content;
  return Object.fromEntries(Spice.filterOptional([[
      "content",
      Spice.optionToJson(Spice.stringToJson, extra)
    ]]));
}

function mystring1_encodeJson(v) {
  let extra = v.content;
  return Object.fromEntries(Spice.filterOptional([[
      "content",
      Spice.optionToJson(Spice.stringToJson, extra)
    ]]));
}

function mystring1_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let content = Stdlib_Option.getOr(Stdlib_Option.map(v["content"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
    TAG: "Ok",
    _0: undefined
  });
  if (content.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        content: content._0
      }
    };
  }
  let e = content._0;
  return Spice.error("." + ("content" + e.path), e.message, e.value);
}

let encoding1 = mystring1_encode;

let a = Spice.optionToJson(Spice.stringToJson, undefined);

console.log(a);

export {
  mystring0_encode,
  mystring0_encodeJson,
  mystring0_decode,
  encoding0,
  mystring1_encode,
  mystring1_encodeJson,
  mystring1_decode,
  encoding1,
  a,
}
/* a Not a pure module */
